kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:privileged-rolebinding
  namespace: development
roleRef:
  kind: Role
  name: psp:privileged-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: naomi # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
