kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:privileged-rolebinding
roleRef:
  kind: Role
  name: psp:privileged-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Namespace
  name: development
