## Priveldge allowed is used applied to the development namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:privileged-role
  namespace: development
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  # resourceName maps to the PSP object
  resourceNames: ["privileged-policy"]
